export const CartActionTypes = {
    TOGGLE_CART_ICON: 'TOGGLE_CART_ICON',
    ADD_ITEM: 'ADD_ITEM',
    LEFT_ARROW_REMOVE_ITEM: 'LEFT_ARROW_REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
};
